workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Flutter Clean
        script: flutter clean
      - name: Flutter Pub Get
        script: flutter pub get
      - name: Check AGP version
        script: |
          cd android
          ./gradlew --version
      - name: Check java version
        script: |
          java -version
      - name: Android Build
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
